### ISSUE TITLE
Hacer más clara la signifcancia en la figura de SAM vertical 

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/shceof#27]
Le agregué una "sombra" a las partes que son significativas. Queda así:

![image](https://user-images.githubusercontent.com/8617595/114102563-e4bfe200-989d-11eb-82ef-5d77a98739df.png)

¿Te parece maś claro, @lbdiaz ?

**Comment by lbdiaz** [comment]
Sí, me parece que con esta visualización se puede distinguir bien lo significativo!
