### ISSUE TITLE
Agregar circulos de latitud

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/shceof#29]
> En las figuras estratósfericas agregar circulos de latitud.

**Comment by eliocamp** [comment]
@lbdiaz ¿A qué figuras en particular le agregaría los círculos?

**Comment by lbdiaz** [comment]
Si no me saltee algunas las figuras serían 1,2,5,6,7,9,14,15.
Por las dudas, para que quede claro, sería hacer algo similar a lo que hicste para el trabaajo que enviaste en las figuras  7 y 10.
