### ISSUE TITLE
Barras de colores en figura 3 (y otras)

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/shceof#30]
> En la figura 3 agregar barra de colores y aclarar unidades (sé que son arbitrarias , pero no es adivinable que las azules y las rojas tienen signos opuestos)

Eso valdría para todas las figuras con escalas arbitrarias (hay un par).

**Comment by eliocamp** [comment]
Lo que podría hacer es agregar en el epígrafe "Negative values in blue, positive values in red" o algo por el estilo, @lbdiaz

**Comment by lbdiaz** [comment]
El tema es que si no está la barra queda un margen de ambiguedad sobre como es la escala de colores, su crecimiento, donde está el 0, etc. Se que no aporta mucho desde lo numérico, pero es lo más conveniente agregarla
