### ISSUE TITLE
¿Sacar figuras de correlación con onda 1 de O3 y PŜA?

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/shceof#34]
> La figura 11 se puede no mostrar y solamente hacer referiencia en el texto a que se calcularon las correlaciones y lo que dieron, y hacer la discusión con eso (tampoco es que se estaba diciendo mucho más).

![image](https://user-images.githubusercontent.com/8617595/114194958-63606200-9926-11eb-9a94-b916153cd971.png)

>  La figura 12 la convertiría en una tabla con la información de los valores de correlación. Si consideras que ver el scatter aporta mucha información extra, se podría agregar de figura suplementaria.

![image](https://user-images.githubusercontent.com/8617595/114194990-6b200680-9926-11eb-8b02-2950b2db3b92.png)

Sé que es mucho espacio, pero en general me gusta mostrar los datos crudos si es posible; por transparencia. Una correlación puede esconder un montón de relaciones distintas. Me gustaría dejarlo por ahora, total siempre hay tiempo para sacar figuras. ¿Qué te parece, @lbdiaz ?

**Comment by lbdiaz** [comment]
Entiendo lo que decis, pero lo que me parece es que para mostrarlas debería estar más justificado por el peso de la discusión en el texto (no es que digas mucho más que si estás correlacionadas linealmente o no). Para conservarlas, las mandaría como figuras suplementarias
