### ISSUE TITLE
Gráficos

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/shceof#41]
Actualizar la pinta de los gráficos a como está [asymsam](https://github.com/eliocamp/asymsam). 

- [x] Recuadro en la leyenda
- [x] Cuadrícula de lon lat + etiquetas
- [x] Espacio entre paneles

**Comment by eliocamp** [comment]
Epígrafes:

- [x] Unidades   
    Chequear unidades de geopotencial, que está en ERA está en m^2/s^2. Cambiar epígrafes o dividir por 9.8 para convertirlo en metros. 
- [x] Período
- [x] Explicación de significancia

**Comment by eliocamp** [comment]
¿Qué te parece, @lbdiaz ?

![image](https://user-images.githubusercontent.com/8617595/129271912-267e68df-f070-4afa-bb8a-de590cf155b9.png)

**Comment by lbdiaz** [comment]
a eso apuntaba el comentario, así que me parece bien ahora! Un detalle sobre la escala de función corriente, los valores negativos quedan un poco superpuestos (quizás achicando un poco la fuente queda más prolijo?)

**Comment by eliocamp** [comment]
Sí, lo noté después de ponerlo acá. Así es más chico. 

![image](https://user-images.githubusercontent.com/8617595/129272812-812da2ff-aa41-401d-8406-333b83b7392f.png)

**Comment by lbdiaz** [comment]
si es mucho lío no, pero quizás sería un poco más prolijo si pones alguna barrita negra para cada label en la barra de colores, así queda más claro a qué color corresponde cada número (comentario válido para otras figuras)

**Comment by eliocamp** [comment]
![sst-psi-1-1](https://user-images.githubusercontent.com/8617595/129274265-29c62c59-abcf-4237-82e8-ff391799437e.png)

**Comment by lbdiaz** [comment]
ahí me parece que queda más claro!

**Comment by eliocamp** [comment]
Acá cambios sutiles en la Figura 3 (extended-series). 

![image](https://user-images.githubusercontent.com/8617595/129372697-d341f15f-8b55-4e11-98fa-033b75ce5ccc.png)

Le saqué el "EOF" de la izquierda, le agregué un eje a los paneles derechos, le puse marcas verticales cada 2 años y puntos a las líneas, para que sea más fácil identificar el valor de cada año si une quiere. 

Eso último se ve nomás cuando uno hace zoom. 

![image](https://user-images.githubusercontent.com/8617595/129372907-5804dd11-db9f-42bd-8594-d87c81859415.png)

**Comment by eliocamp** [comment]
En un comentario, decís que los puntitos de significancia son muy densos, esto te parece mejor?

![image](https://user-images.githubusercontent.com/8617595/129374515-f610a32c-0abd-40af-b23a-4c2b2515566a.png)

**Comment by lbdiaz** [comment]
La figura de las series me parece que está muy bien así. Mi única observación es que me resulta muy raro no poner los dos primeros números de los años (además de que si alguien saca la figura no es 100% trivial qué significa). Si lo sacaste porque te quedaban muy superpuestos, fijate si no le podemos achicar un poco la letra

Lo de los puntitos me parece que ahora está mejor, pero quizás ya es demasiado y no es tan sencillo verlo bien. Creo que ahora tenes un poco de margen para que queden un poco más visibles

**Comment by eliocamp** [comment]
Le puse las unidades a las escalas de colores y no sé si voy a poder dormir con esta falta de alineación. 

![image](https://user-images.githubusercontent.com/8617595/129789791-b3e66e36-7907-43c6-a7ad-f35a0dcf6fbb.png)

**Comment by lbdiaz** [comment]
si, queda un poco raro eso sobretodo que también tienen una altura distinta las dos barras.
Si ves la forma rápido de mejorarlo, trata de hacerlo, sino dejalo para despues
