### ISSUE TITLE
Método PSA

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/shceof#43]
Cómo describir la metodología de PSA.

Originalmente estaba:

> The Pacific South American patterns (PSA1 and PSA2) were calculated as the third and fourth leading EOF of seasonal mean for 500 hPa geopotential height with all seasons together following Mo and Paegle (2001). 

Esto no está claro.

Mo and Paegle (2001) dice que los PSA son 

> They are the second and third EOF patterns of seasonal mean 500-hPa height anomalies for the SH **with all seasons pooled together**

(mi énfasis)

Lo cambié a: 

> The Pacific South American patterns (PSA1 and PSA2) were calculated as the third and fourth leading EOF of seasonal mean for 500 hPa geopotential height combining all seasons following @mo2001.

Te parece mejor, @lbdiaz ?

**Comment by lbdiaz** [comment]
Me parece que faltaría agregar que son "anomalies" y que son del "SH" y cambiaría que trabajo estás siguiendo al principio
Algo así
"The Pacific South American patterns (PSA1 and PSA2) were calculated following @mo2001 as the third and fourth leading EOF of seasonal mean **anomalies** for **SH** 500 hPa geopotential height combining all seasons .
