### ISSUE TITLE
Descripción de método cEOF

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/shceof#45]
https://github.com/eliocamp/shceof/blob/main/analysis/paper/shceof.Rmd#L414-L415

Originalmente dice:

> Complex Empirical Orthogonal Functions (cEOF) is a useful method to characterise zonal waves, considering phase-varying structures [@horel1984]. This method involves augmenting the original fields with the Hilbert transform of the data and then computing the Singular Value Decomposition of it. In this work, instead of applying the Hilbert transform to the time series at each point, we apply it to each latitude circle at each moment in time. Since each latitude circle is a periodic domain, this procedure does not suffer from edge effects. 

¿Se entiende mejor así, @lbdiaz? 👇

> Complex Empirical Orthogonal Functions (cEOF) is a useful method to characterise zonal waves, considering phase-varying structures [@horel1984]. This method involves computing EOF on the analytic representation of the original field. That is, a complex field in which the real part is the original variable and the imaginary part is the original data shifted by 90\degree at each spectral frequency (e.g. it's Hilbert transform). The Hilbert transform is usually understood in terms of time-varying signal. In this work we apply the Hilbert transform instead to each latitude circle at each moment in time.

**Comment by lbdiaz** [comment]
"Complex Empirical Orthogonal Functions (cEOF) is a useful method to characterise zonal waves, considering phase-varying structures [@horel1984]. This method involves computing EOF on the analytic representation of the original field. **This representation** is a complex field in which the real part is the original variable and the imaginary part is the original data shifted by 90\degree at each spectral frequency (e.g. its Hilbert transform). The Hilbert transform is usually understood in terms of time-varying signal. **However**, In this work we apply the Hilbert transform to each latitude circle at each moment in time."

Te puse unos leves cambios. Una duda que me queda es si cuando decis "e.g. its Hilbert transform" es un ejemplo posible o debería ser "i.e. it's Hilbert transform"" (no lo pondría entre parentésis)

**Comment by eliocamp** [comment]
Sí, es "i.e.". Me pasa por no googlear la diferencia entre e.g. e i.e., como tengo que hacer cada vez que escribo alguno de esos

**Comment by lbdiaz** [comment]
Debes haber estado estudiando poco latín XD

**Comment by fipoucat** [comment]
Hi, 

This is indeed an interesting package and think it could help me on detecting 3-5 days period waves at 700 hPa from uwind? wonder if you think this is possible and maybe you have an example script I could adapt for this.

Cheers
