### ISSUE TITLE
Figura fig:extended-series despareja?

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/shceof#46]
> Revisa la figura 4 que te están quedando bastante desparejos los subplots.

¿A qué te referís con que están desparejos, @lbdiaz? Esta es la figura (ahora con colores!):

![image](https://user-images.githubusercontent.com/8617595/120668725-1cde3e00-c465-11eb-8e24-4502fbb4e919.png)

**Comment by lbdiaz** [comment]
Lo que yo veo raro es que las figuras no están alineadas respecto al cero (que se ve en el lado izquierdo). Me parece que también confunden las líneas que están a los costados. También podría ayudar si le agregas un grid a cada uno, para que se puedan seguir mejor los valores

**Comment by eliocamp** [comment]
Las figuras sí están alineadas. Sólo que la línea horizontal marca el valor medio en vez del cero (que no es cero en para el cEOF1). Las líneas que están a los costados marcan el rango de los datos. Quizás tengo que poner todo eso en el epígrafe.

**Comment by lbdiaz** [comment]
¿Entonce el epígrafe estaría mal? Porque dice "Each series is scaled to zero mean..."
A mí me parece confusa como está. Creo que quedaría mejor si agregas un grid y lo del valor medio y el rango lo pones solo en un costado (¿se entiende?). Me queda la duda también si no conviene que tengan el mismo rango  las del cEOF1 y cEOF2, porque sino da la idea de que una tiene mucha mayor variabilidad que la otra

**Comment by eliocamp** [comment]
Si, me di cuenta recién luego de responder. Me parece que al principio la idea era centrarlo y escalarlo pero luego se me ocurrió que quizás está bueno mantener el promedio porque así queda más claro que la tendencia de cEOF1 Real no implica un cambio de signo. 

Esto sería escalando:

![image](https://user-images.githubusercontent.com/8617595/121037479-dc90ff80-c785-11eb-8579-00e0b6620ec7.png)

**Comment by lbdiaz** [comment]
Ahí queda más claro. Igual me parecía bien como lo estabas haciendo (deja claro por ej. que el cEOF1 real siempre está con la misma fase), pero me parece que quedaría visualmente más claro con las sugerencias que te hice.

**Comment by eliocamp** [comment]
¿Esta? Ahí arreglé una grilla y puse el rangeframe sólo a la derecha. 

![image](https://user-images.githubusercontent.com/8617595/121074658-897d7380-c7aa-11eb-9017-0177ba7a69c0.png)

**Comment by lbdiaz** [comment]
¡Ahora me parece más clara! ¿Qué opinas sobre poner las 4 con el mismo rango? sino parece a primera vista que cEOF2 Im tiene muchisima más variabilidad que  cEOF1 Re.
(y no te olvides de revisar qué el caption quede completo después)

**Comment by eliocamp** [comment]
Con mismo rango te referís a estandarizar para que tengan desvío estandar 1 pero no cambiar la media?

**Comment by lbdiaz** [comment]
No. Me refería al gráfico, a usar la misma escala en los de arriba y abajo

**Comment by eliocamp** [comment]
Ahh, ok. Así:

![image](https://user-images.githubusercontent.com/8617595/121076521-e712bf80-c7ac-11eb-93da-314405b77864.png)

El problema de eso es que se desperdicia mucho espacio.

**Comment by lbdiaz** [comment]
si, era de esperar. Así me parecen más informativas desde lo visual, aunque pueden ser un poco menos si alguien quiere pararse en un tiempo. En todo caso, se me ocurre que se pueden hacer un poco más altas.

**Comment by eliocamp** [comment]
Ahí va más alta. 

![image](https://user-images.githubusercontent.com/8617595/121078430-58537200-c7af-11eb-8d1f-0a7705600026.png)


Estoy pensando que con esta figura, la Figura 3 (que es lo mismo pero hata 1979) es redundante.

**Comment by lbdiaz** [comment]
Sí, es cierto. Mejor dejar solo esta figura. Aunque algo que podrías agregar es una línea horizontal que indique el cambio de dataset y para aclarar que solo el último período utilizaste para calcular los modos en sí.
