### ISSUE TITLE
wave detection

### ISSUE THREAD

**Issue by fipoucat** [eliocamp/shceof#47]
Hi,

This is indeed an interesting package and think it could help me on detecting 3-5 days period waves at 700 hPa from uwind? wonder if you think this is possible and maybe you have an example script I could adapt for this.

Cheers

**Comment by eliocamp** [comment]
Honestly I have no idea! If you want to detect waves on a particular bandwidth I'd guess the most straightforward method would be a band-pass filter and then compute the wave envelope. `metR::WaveEnvelope()` can help you with that last step (but it's relatively easy to do it in R, the code for that function is just 5 lines long), but I have no experience with band-pass filters.

**Comment by fipoucat** [comment]
THank you for that, for the bandwidth these wave are detected between 2 to
10 days, they are of 2 types the african easterly waves (3 to 5 days) and
the others which are 6 to 9 days. The work I saw uses a high-pass filter
like Butterworth or something similar. The typical levels they are detected
are 700 or 650 hPa and controle more than 70% of West Africa rainfall.
