### ISSUE TITLE
"Synthetic"

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/shceof#49]
> To test the hypothesis that a PSA-like feature can appear as statistic contamination of an otherwise zonally symmetrical and uncorrelated SAM, we create a synthetic dataset of `r uniqueN(fake_sam$time)` fields by reconstructing the SON 200 hPa geopotential height field explained by the cEOF2 and adding a perfectly zonally symmetric SAM-like structure with random sign and value sampled with replacement from the real SAM index.
> To this synthetic dataset we then apply traditional EOF.

Acá pusiste que no te gusta "synthetic", @lbdiaz . Por lo que ví, [es un término usado](https://www.google.com/search?q=synthetic+dataset+generation). También podría usar "fake data", pero "fake" tiene connotaciones negativas. Se me ocurre también "simulated", pero siento que esa palabra tiende a implicar que hay un proceso generador detrás. En este caso, son básicamente números aleatorios.

**Comment by lbdiaz** [comment]
Ok.  Parece ser el término más conveniente considerando el uso
