### ISSUE TITLE
Etiquetas para las componentes de los datos sintéticos

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/shceof#50]
![image](https://user-images.githubusercontent.com/8617595/121923964-d8c72500-cd11-11eb-82b9-9af3e9e5496f.png)

Esto es cierto que no es realmente el SAM. ¿Si pongo "Pseudo-SAM" queda mejor? @lbdiaz 

![image](https://user-images.githubusercontent.com/8617595/121924128-001df200-cd12-11eb-90a8-89f832c8bf84.png)

Podría ponerle "S-SAM", ya que es básicamente lo que es.

**Comment by lbdiaz** [comment]
me parece que sería mejor llamarlo "S-SAM" si es exactamente eso. Esta parte creo que va a ver que revisarla con bastante cuidado para que se entienda bien

**Comment by eliocamp** [comment]
Mh.. Ahí? "Annular pattern" para no darle un nombre específico, porque no importa. Es el patrón zonalmente simétrico del SAM, pero no es muy importante eso. 

![image](https://user-images.githubusercontent.com/8617595/121941184-55afca00-cd25-11eb-9ef8-d08ca607af69.png)

También tengo que cambiarle el signo a los de abajo para que coincidan con los de arriba.
