### ISSUE TITLE
Barra de colores para streamfunction

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/shceof#51]
> Revisa los labels de la colorbar para la figura 13. Además ojo que solamente sirven para la columna a, faltan los correspondientes a la streamfunction y el vector de referencia para wave flux

![image](https://user-images.githubusercontent.com/8617595/122130171-a00c7600-ce0d-11eb-86fb-56614be23f77.png)

¿Hace falta la barra para el streamfunction? Son valores nedui arbitrarios en definitiva, no?  @lbdiaz

**Comment by lbdiaz** [comment]
Lo que pasa es que aunque no sea tan importante el valor en sí, hay varias características del grafico que sino se las tiene que imaginar quien lo vaya a leer (que los rojos son positivos, los azules negativos, que la escala lineal, que lo que está en blanco está cerca de 0, etc....), por eso es lo más fácil (aunque no sea tan relevante su magnitud). No sé si te lo dije antes pero me resulta un poco saturada la figura con los "fluxes", ¿te parece hacerlos un poco menos gruesos?

**Comment by eliocamp** [comment]
¿Te parece así?

![image](https://user-images.githubusercontent.com/8617595/123978602-5f2c6980-d996-11eb-8025-3d0a7531c375.png)

**Comment by lbdiaz** [comment]
Me parece que quedaría más prolijo si pones cada barra de colores debajo de la respectiva columna.

Me queda la duda ahora que lo veo con los valores de streamfunction. No deberían tener valores arbitrarios, porque si usas la definición que se suele usar (para que cuando tomes el rotor quede la velcoidad) te quedan del orden de 10^7

**Comment by eliocamp** [comment]
> Me parece que quedaría más prolijo si pones cada barra de colores debajo de la respectiva columna.

Sí, pero queda demasiado chica la barra, me parece y se superponen las etiquetas.

> Me queda la duda ahora que lo veo con los valores de streamfunction. No deberían tener valores arbitrarios, porque si usas la definición que se suele usar (para que cuando tomes el rotor quede la velcoidad) te quedan del orden de 10^7

Estuve chequeando esto. Creo que el tema es que la ecuación que estoy resolviendo para invertir el laplaciano tiene una constante dando vueltas que ignoré completamente. Si hago la comparación con la función corriente que viene de NCEP, el correlación es virtualmetne 1 pero a falta de una constante multiplicativa y de ~4e^13 y una aditiva de ~-2.3e^6. No le di pelota porque  la constante aditiva es literalmente aleatoria (creo que depende de la condición de contorno) y se va cuando tomo anomalías / regresiones, y la multiplicativa tampoco importa demasiado porque no cambia los patrones que se ven en el gráfico. 

Podría tratar de resolverlo de fondo en la rutina resuelve la ecuación, pero eso implica voler a entender a fondo la ecuación y el  código de FORTRAN a medio documentar. Como en definitiva no es imporante, creo que mejor simplemente multiplico y sumo esos números.

**Comment by lbdiaz** [comment]
la constante aditiva, no me preocupa mucho, pero sería importante que la multiplicativa sea correcta para que de una velocidad consistente
