### ISSUE TITLE
Pesado por el ceof

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/shceof#52]
> ¿Qué significa para el fit "weighted by the magnitude of cEOF2

![image](https://user-images.githubusercontent.com/8617595/122130551-2de86100-ce0e-11eb-869b-f98f6b5b9c79.png)

Estoy haciendo una regresión lineal con pesos y el peso es la magnitud del cEOF2. "...computed by weighted OLS using the magnitude of the cEOF2 as weights" es más claro? @lbdiaz

**Comment by lbdiaz** [comment]
Me parece bien
