### ISSUE TITLE
Correlación con ENSO

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/shceof#53]
@lbdiaz  dijo:
> Se que la cantidad de años hace bastante limitada la muestra, pero creo que es un resultado a tener en cuenta que en esos eventos muy intensos se alineen. ¿Probaste hacer la correlación con todos los puntos naranjas?

La correlación con sólo los naranjas es alta: 0.64 (CI: 0.29 -- 0.84)

Pero mirando al scatterplot no la veo muy confiable:

![image](https://user-images.githubusercontent.com/8617595/122131398-810ee380-ce0f-11eb-8238-3bb9a0a27c5a.png)

Escencialmente toda la correlación sale por esos tres puntitos arriba a la derecha. 

Sacando esos puntitos, la correlación usando sólo los puntos naranjas es no significativa (0.17 (CI: -0.33 -- 0.59))

**Comment by lbdiaz** [comment]
quizás entonces se puede comentar que los eventos más intensos de ONI se asociaron con eventos cEOF intensos, aunque en general, la relación no es significativa
