### ISSUE TITLE
Cómo escribir la ecuación

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/shceof#54]
¿Cómo escrbir esta ecuación?

@lbdiaz dijo:
> La formula en la figura trata de escribirla en una forma más precisa ”precipitación”/”phase” son muy generales

Agregué las unidades, aunque queda bastante feo y tengo que averguar bien si se puede mejorar.

![image](https://user-images.githubusercontent.com/8617595/122132686-b288ae80-ce11-11eb-9eb7-427122e1320d.png)

¿Qué sería mejor poner en el nombre de las variables?

**Comment by lbdiaz** [comment]
me parece que sería mejor en vez de decir "precipitation" ponerle algun nombre a la región como para que sea "Reg_precipitation". Las unidades creo que se pueden omitir y aclararlo en el caption

**Comment by eliocamp** [comment]
Ahí? 

![image](https://user-images.githubusercontent.com/8617595/127022562-25e68c23-89d1-45d0-82e4-3353ac7a5a4b.png)

**Comment by lbdiaz** [comment]
Creo que todavía se puede mejorar un poco la estética, pero lo vemos con la versión completa
