### ISSUE TITLE
Aclarar terminología

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/shceof#55]
¿A qué terminología te referís acá, @lbdiaz ?

![image](https://user-images.githubusercontent.com/8617595/127177350-bad1b6ce-a896-4459-87cb-460c5abb5190.png)

**Comment by lbdiaz** [comment]
mmm, no te sabría decir ahora. Por ahí después cuando lea bien la nueva versión me doy cuenta a qué apuntaba

**Comment by eliocamp** [comment]
Ok, lo cierro por ahora enonces.
